spring:
  datasource: #数据源的相关配置
    type: com.zaxxer.hikari.HikariDataSource  #数据源类型：HikariCP
    driver-class-name: com.mysql.jdbc.Driver #mysql驱动
    url: jdbc:mysql://localhost:3306/jiagou?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
  elasticsearch:
    rest:
      uris: http://152.136.125.49:9200
      username: chen
      password: chen
#  data:
#    elasticsearch:
#      cluster-name: elasticsearch
#      cluster-nodes: 152.136.125.49:9300


server:
  port: 8099
