spring:
  datasource:                                             ## 数据源的相关配置
    type: com.zaxxer.hikari.HikariDataSource              # 数据源 HikariCP
    driver-class-name: com.mysql.jdbc.Driver              # mysql驱动
    url: jdbc:mysql://localhost:6022/itzixi-pay?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: 123456
  redis:
    port: 6379
    password: yuyi
    database: 0
    host: 121.41.113.243

