server:
  port: 8090
spring:
  datasource: #数据源的相关配置
    #type: com.zaxxer.hikari.HikariDataSource  #数据源类型：HikariCP
    #  driver-class-name: com.mysql.jdbc.Driver #mysql驱动
    url: jdbc:mysql://localhost:3306/jiagou?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    # username: root
    # password: 123456
  redis:
    # password: cnh123
    #  database: 1
    #单机模式
    database: 0
    host: 152.136.125.49
    port: 6379
    password: cnh123
    #哨兵模式
#    cluster:
#      nodes: 192.168.124.37,192.168.124.28,192.168.124.30,192.168.124.32,192.168.124.33,192.168.124.34
#    password: cnh123
#    sentinel:
#      master: mymaster
#      nodes: 192.168.124.31,192.168.124.21,192.168.124.24
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl